[package]
name = "yanet-ping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yanet-core = { path = "../yanet-core" }
futures-timer = { version = "3.0.2" }
futures-micro = { version = "1.0.0-rc0" }
